Обработка исключений
====================

* `Исключения и их обработка`: [Исключения и их обработка](http://kostin.ws/java/java-exceptions.html)
* `Глава 10 Обработка исключений`: [Глава 10 Обработка исключений](http://www.softzenware.com/java/10.htm)
* `Исключения в Java, Часть I (try-catch-finally)`: [Исключения в Java, Часть I (try-catch-finally)](http://habrahabr.ru/company/golovachcourses/blog/223821/)
* `Исключения в Java, Часть II (checked/unchecked)`: [Исключения в Java, Часть II (checked/unchecked)](http://habrahabr.ru/company/golovachcourses/blog/225585/)
* `Java / Типы исключений в Java`: [Java / Типы исключений в Java](http://www.quizful.net/interview/java/exception-types)
* `http://aectann.wikidot.com/java-exceptions-handling`: [http://aectann.wikidot.com/java-exceptions-handling](http://aectann.wikidot.com/java-exceptions-handling)


###Описание

> Исключение происходит когда прграмма неможет продолжать выполнение ТОГДА в этом случае Java-машина создаем объект-исключения И переключается на него ЧТОБЫ пользователь мог корректно завершить работу с этой програмой.

> Относительно области применения исключения бывают: "аппаратные", "внешние", "программные":

1. `Error`: исключительные ситуации (серъезные ошибки) которые связаны при работе JAVA-машины на аппаратном уровне (железом) - их нет смысла вообще никак обрабатывать, потому-что они в принципе неподдерживаются этой JAVA-машиной

3. `RuntimeException`: исключительные ситуации (неконтролируемые ошибки) которые связаны с передачей внешних данных ИХ наличие невозможно предугадать на конкретный момент времени - их необизательно обрабатывать как исключения (нужно использовать проверку валидности по условию)...

2. `Exception`: исключительные ситуации (контролируемые ошибки) которые связаны при работе внутри программы ИХ наличие можно и нужно предугадывать - их нужно обрабатывать как исключения!


> Все объекты-исключения имеют общего предка - "Trowable".

> Иерархическую структуру для объектов-исключения можно разделить на 3-группы: "Error" (аппаратные), "RuntimeException" (внешние, которые тоже наследуются от Exception), "Exception" (программные)

> Также все исключения можно разделить на 2-группы:

>> "CHECKED" (контролируемые исключения) - сюда относятся только "Exception" (программные) исключения

>> "UNCHECKED" (неконтролируемые исключения) - сюда относятся "Error" (аппаратные) и "RuntimeException" (внешние) исключения



> Существует особая разница для понимания: ВОЗБУДИТЬ ИСКЛЮЧЕНИЕ и БРОСИТЬ ИСКЛЮЧЕНИЕ.
>> "исключительная ситуация" - это непредвиденный случай при выполнении чего-то (когда программа ведет себя ненормально и JAVA-машина незнет как с этим работать)... - такое поведение программы приводит к "возбуждению исключения".
"возбужденные исключения" они обрабатываются по умолчанию виртуальной JAVA-машинной, тобишь, объекты-исключения автоматичнски создаются испольняющей средой JAVA - после этого JAVA-машина прекращает (нормальную) работу программы и переклячается на объекты-исключения, которые позволяют корректно завершить для пользователя работу с этой программой

>> Если нужно какую-то конкретную ошибку допонительно обработать (например: проверка на NULL|0, проверка на отрицательное значение, ...) - в этом случае можно "бросить исключение", чтобы потом его обработать в блоке "catch"...

>> Блок "catch" обычно служит для того чтобы ловить какие-нибудь "RuntimeException" (UNCHECKED) исключения для дополнительной обработки.

>> Блок "try" может иметь несколько/много блоков "catch" чтобы ловить разные типы ошибок И эти типы-исключений для ошибок должны быть выстроены в порядке с-низу в-верх (сперва обрабатывается самый нижный-класс по иерархии, а в конце самый верхний).

>> Самым последним нужно ставить блок "finally" - это гарантия на случай если ниодин из блоков "catch" небудет задействован/найден.

>> И поскольку Блок "try" позволяет иметь много блоков "catch". Также и метод может иметь много разных типов исключений которые он бросает

>> Бросить исключение можно несколькими способами:
>>> Можно перехватывать брошенное исключение (на случай если такие будут) в блоке "try", чтобы потом в блоке "catch" его отловить и обработать - но это только на тот случай если такие будут

>>> А можно принудительно/гарантированно бросить объект-исключения с помощью "throw" (исключение-throw можно бросить либо в блоке "try/catch" либо пометить метод как "throws" что он может возбуждать исключения типа объекта-исключения) - при этом (нормальное) выполнение программы тут-же прервется


###Резюме

>> Тобишь, блок try/catch/finally служит чтобы перехватывать исключения для дополнительной обработки.

>> если будет (возбуждена или брошена) исключительная ситуация JAVA-машина сама в любом случае будет ловить и обработать (по умолчанию) его, даже без try/catch...

>> после того как принудительно будет брошено исключение "throw" - после этого (нормальное) выполение программы прервется и JAVA-машина переключиться на объект-исключения

>> объекты-исключения (которые способны их возбуждать/перехватывать/ловить) могут использоваться библиотечные или могут быть созданы...


К `Error` (UNCHECKED) можно отнести: OutOfMemoryError, VirtualMachineError, StackOverflowError, NoSuchMethodError

К `RuntimeException` (UNCHECKED) можно отнести: NullPointetrException, IndexOutOfBoundsException, ArrayIndexOutOfBoundsException, ArichmeticException, IllegalArgumentException

К `Exception` (CHECKED) можно отнести: IOException, EOFException, ObjectStreamException, InterrupteException


###Ссылки

* [Создание собственного исключения/Exception](https://code.google.com/p/nc-training-5/wiki/TryCatchException)
* [пример, как правильно работать с RuntimeException](http://habrahabr.ru/post/183322/)
* [Почему используем System.err, а не System.out](http://habrahabr.ru/company/golovachcourses/blog/223821/)
* `проверка на cheched исключения происходит в момент компиляции, а перехват исключений (catch) происходит в момент выполнения` [Поведение компилятора/JVM](http://habrahabr.ru/company/golovachcourses/blog/225585/)
* [Классификация исключений](http://neerc.ifmo.ru/wiki/index.php?title=Обработка_ошибок_и_исключения)
* [Встроенные исключения Java](http://developer.alexanderklimov.ru/android/java/exception.php)
* `Наличие\обработка Checked исключения проверяются на этапе компиляции, Наличие\обработка Unchecked исключения происходит на этапе выполнения` [Checked исключения отличаются от Unchecked исключения в Java, тем что](http://www.quizful.net/post/java-exceptions)

> Создание собственного исключения/Exception
>> Делится на создание собственного класса исключений, вызов его из необходимого участка функции/процедуры и указание спецификации данного исключения в заглавии функции/процедуры (если исключение контролируемое).


> Проверяемые исключения (Все исключения, кроме "Error" и "RuntimeException" являются проверяемыми)
>> Наследники класса Exception являются проверяемыми исключениями (checked exception). Как правило это ошибки возникшие по вине внешних обстоятельств или пользователя приложения (неправильно указали имя файла). Эти исключения должны обрабатываться в ходе работы программы, поэтому компилятор проверяет наличие обработчика или явного описания тех типов исключений, которые могут быть сгенерированы некоторым методом.


>  Error
>> Класс Error и его подклассы предназначены для системных ошибок. Свои собственные классы-наследники для Error писать не нужно. Как правило, это действительно фатальные ошибки, пытаться обработать которые довольно бессмысленно (например OutOfMemoryError).


>  RuntimeException
>> Эти исключения обычно возникают в результате ошибок программирования, такие как ошибки разработчика или неверное использование интерфейса приложения. Например, в случае выхода за границы массива метод бросит OutOfBoundsException. Такие ошибки могут быть в любом месте программы, поэтому компилятор не требует указывать runtime исключения в объявлении метода. Теоретически приложение может поймать это исключение, но разумнее исправить ошибку.


> Список проверяемых системных исключений, которые можно включать в список throws
>> ArithmeticException, ArrayIndexOutOfBoundsException, ArrayStoreException, ClassCastException, EnumConstantNotPresentException, IllegalArgumentException, IllegalMonitorStateException, IllegalStateException, IllegalThreadStateException, IndexOutofBoundsException, NegativeArraySizeException, NullPointerException, NumberFormatException, SecurityException, StringIndexOutOfBounds, TypeNotPresentException, UnsupportedOperationException


> список непроверяемых исключений
>> ClassNotFoundException, CloneNotSupportedException, IllegalAccessException, InstantiationException, InterruptedException, NoSuchFieldException, NoSuchMethodException, ReflectiveOperationException


> Checked исключения (Exception) - это те которые должны обрабатываться блоком catch или описываться в сигнатуре метода. Unchecked (RuntimeException) могут не обрабатываться и не быть описанными
>> Checked исключения должны описываться в сигнатуре метода через throws или обрабатываться блоком try/catch/finally.